<a href="https://colab.research.google.com/github/Meshi1520/Deep-learning/blob/main/deep_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers
import pandas as pd

In [ ]:
df = pd.DataFrame({ 'soil_moisture': [12, 18, 22, 28, 35, 40, 15, 20, 25, 30, 14, 32, 38, 17, 27, 42],
                   'temperature_C': [36, 34, 31, 29, 27, 25, 37, 33, 30, 28, 35, 26, 24, 32, 29, 23],
                    'sunlight_hours': [11, 10, 8, 7, 6, 5, 12, 9, 8, 7, 11, 6, 5, 9, 7, 4],
                    'needs_water': [1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0] })

In [ ]:
df

    soil_moisture  temperature_C  sunlight_hours  needs_water
0              12             36              11            1
1              18             34              10            1
2              22             31               8            1
3              28             29               7            0
4              35             27               6            0
5              40             25               5            0
6              15             37              12            1
7              20             33               9            1
8              25             30               8            0
9              30             28               7            0
10             14             35              11            1
11             32             26               6            0
12             38             24               5            0
13             17             32               9            1
14             27             29               7            0
15             42             23               4            0

In [ ]:
df.columns

Index(['soil_moisture', 'temperature_C', 'sunlight_hours', 'needs_water'], dtype='object')

In [ ]:
X = df[['soil_moisture', 'temperature_C', 'sunlight_hours']]
y = df['needs_water']
# we need to scale these values  for temperature for values between 0 and 1 which is normalization and standardization mean - 0 and sd = 1 with values between -3 and 3

In [ ]:
# we do normalization here
X_min = X.min()
X_max = X.max()
X_scaled = (X-X_min)/(X_max-X_min + 1e-8)

In [ ]:
X

    soil_moisture  temperature_C  sunlight_hours
0              12             36              11
1              18             34              10
2              22             31               8
3              28             29               7
4              35             27               6
5              40             25               5
6              15             37              12
7              20             33               9
8              25             30               8
9              30             28               7
10             14             35              11
11             32             26               6
12             38             24               5
13             17             32               9
14             27             29               7
15             42             23               4

In [ ]:
X_scaled

    soil_moisture  temperature_C  sunlight_hours
0        0.000000       0.928571           0.875
1        0.200000       0.785714           0.750
2        0.333333       0.571429           0.500
3        0.533333       0.428571           0.375
4        0.766667       0.285714           0.250
5        0.933333       0.142857           0.125
6        0.100000       1.000000           1.000
7        0.266667       0.714286           0.625
8        0.433333       0.500000           0.500
9        0.600000       0.357143           0.375
10       0.066667       0.857143           0.875
11       0.666667       0.214286           0.250
12       0.866667       0.071429           0.125
13       0.166667       0.642857           0.625
14       0.500000       0.428571           0.375
15       1.000000       0.000000           0.000

In [ ]:
#the deep learning model works well with these valu

In [ ]:
 X_train, X_test, y_train, y_test = train_test_split( X_scaled, y, test_size=0.33, random_state=42)

In [ ]:
model = keras.Sequential([
    #first layer is input
    layers.Input(shape=(X_train.shape[1],)),
    layers.Dense(8, activation='relu'),
    # ouutput layer
    layers.Dense(1, activation = 'softmax')
])

In [ ]:
# optimizer
model.compile(optimizer = 'sgd', loss = 'binary_crossentropy',metrics= ['accuracy'])

In [ ]:
history_full = model.fit(X_train,y_train,epochs = 100,batch_size = len(X_train),verbose = 1)

history = model.fit(
    X_train.values,y_train.values,
    validation_data = (X_test.values,y_test.values),
    epochs = 100,
    batch_size = 3,
    verbose = 1 # show what is being in data training
    #batch_size if we have 10k data points and it will take one row but if we put batch it willtaek rows in batches)
#save your training
)
history_minibatch = model.fit(X_train,y_train,epochs = 100,batch_size = 100,verbose = 4)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.4000 - loss: 0.6689
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.4000 - loss: 0.6684
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.4000 - loss: 0.6680
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.4000 - loss: 0.6676
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.4000 - loss: 0.6672
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.4000 - loss: 0.6668
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.4000 - loss: 0.6664
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.4000 - loss: 0.6660
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.4000 - loss: 0.6656
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.4000 - loss: 0.6652
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.4000 - loss: 0.6648
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.4000 - loss: 0.6644
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.4000 - loss: 0.6640
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.4000 - loss: 0.6636
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.4000 - loss: 0.6632
Epoch 16/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.4000 - loss: 0.6628
Epoch 17/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.4000 - loss: 0.6624
Epoch 18/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.4000 - loss: 0.6620
Epoch 19/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.4000 - loss: 0.6616
Epoch 20/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.4000 - loss: 0.6612
Epoch 21/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.4000 - loss: 0.6608
Epoch 22/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.4000 - loss: 0.6604
Epoch 23/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.4000 - loss: 0.6600
Epoch 24/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.4000 - loss: 0.6596
Epoch 25/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.4000 - loss: 0.6592
Epoch 26/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.4000 - loss: 0.6589
Epoch 27/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.4000 - loss: 0.6585
Epoch 28/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.4000 - loss: 0.6581
Epoch 29/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.4000 - loss: 0.6577
Epoch 30/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.4000 - loss: 0.6573
Epoch 31/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.4000 - loss: 0.6569
Epoch 32/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.4000 - loss: 0.6565
Epoch 33/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.4000 - loss: 0.6561
Epoch 34/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.4000 - loss: 0.6557
Epoch 35/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.4000 - loss: 0.6553
Epoch 36/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.4000 - loss: 0.6549
Epoch 37/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.4000 - loss: 0.6545
Epoch 38/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.4000 - loss: 0.6541
Epoch 39/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.4000 - loss: 0.6538
Epoch 40/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.4000 - loss: 0.6534
Epoch 41/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.4000 - loss: 0.6530
Epoch 42/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.4000 - loss: 0.6526
Epoch 43/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.4000 - loss: 0.6522
Epoch 44/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.4000 - loss: 0.6518
Epoch 45/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.4000 - loss: 0.6514
Epoch 46/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.4000 - loss: 0.6510
Epoch 47/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.4000 - loss: 0.6506
Epoch 48/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.4000 - loss: 0.6502
Epoch 49/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.4000 - loss: 0.6499
Epoch 50/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.4000 - loss: 0.6495
Epoch 51/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.4000 - loss: 0.6491
Epoch 52/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.4000 - loss: 0.6487
Epoch 53/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.4000 - loss: 0.6483
Epoch 54/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.4000 - loss: 0.6479
Epoch 55/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.4000 - loss: 0.6475
Epoch 56/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.4000 - loss: 0.6472
Epoch 57/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.4000 - loss: 0.6468
Epoch 58/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.4000 - loss: 0.6464
Epoch 59/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.4000 - loss: 0.6460
Epoch 60/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.4000 - loss: 0.6456
Epoch 61/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.4000 - loss: 0.6452
Epoch 62/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.4000 - loss: 0.6448
Epoch 63/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.4000 - loss: 0.6445
Epoch 64/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.4000 - loss: 0.6441
Epoch 65/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.4000 - loss: 0.6437
Epoch 66/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.4000 - loss: 0.6433
Epoch 67/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.4000 - loss: 0.6429
Epoch 68/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.4000 - loss: 0.6425
Epoch 69/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.4000 - loss: 0.6421
Epoch 70/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.4000 - loss: 0.6418
Epoch 71/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.4000 - loss: 0.6414
Epoch 72/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.4000 - loss: 0.6410
Epoch 73/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.4000 - loss: 0.6406
Epoch 74/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.4000 - loss: 0.6402
Epoch 75/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.4000 - loss: 0.6398
Epoch 76/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.4000 - loss: 0.6394
Epoch 77/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.4000 - loss: 0.6391
Epoch 78/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.4000 - loss: 0.6387
Epoch 79/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.4000 - loss: 0.6383
Epoch 80/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.4000 - loss: 0.6379
Epoch 81/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.4000 - loss: 0.6375
Epoch 82/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.4000 - loss: 0.6371
Epoch 83/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.4000 - loss: 0.6368
Epoch 84/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.4000 - loss: 0.6364
Epoch 85/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.4000 - loss: 0.6360
Epoch 86/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.4000 - loss: 0.6356
Epoch 87/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.4000 - loss: 0.6352
Epoch 88/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.4000 - loss: 0.6348
Epoch 89/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step - accuracy: 0.4000 - loss: 0.6345
Epoch 90/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.4000 - loss: 0.6341
Epoch 91/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.4000 - loss: 0.6337
Epoch 92/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - accuracy: 0.4000 - loss: 0.6333
Epoch 93/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - accuracy: 0.4000 - loss: 0.6329
Epoch 94/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.4000 - loss: 0.6325
Epoch 95/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.4000 - loss: 0.6322
Epoch 96/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.4000 - loss: 0.6318
Epoch 97/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - accuracy: 0.4000 - loss: 0.6314
Epoch 98/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - accuracy: 0.4000 - loss: 0.6310
Epoch 99/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step - accuracy: 0.4000 - loss: 0.6306
Epoch 100/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.4000 - loss: 0.6302
Epoch 1/100

/usr/local/lib/python3.12/dist-packages/keras/src/ops/nn.py:947: UserWarning: You are using a softmax over axis -1 of a tensor of shape (None, 1). This axis has size 1. The softmax operation will always return the value 1, which is likely not what you intended. Did you mean to use a sigmoid instead?
  warnings.warn(

ValueError: Cannot take the length of shape with unknown rank.

In [ ]:
# then we have monotonous gradient descent
# wher noise is just always created
# they made momentum
# with sgd stochastic graadient descent
# it also showed local minima and global minima both

In [ ]:
from tensorflow.keras import optimizers
opt = optimizers.SGD(learning_rate = 0.01,momentum = 0.9)